<?php
/**
  * Recent_Posts widget class
  *
  */
class WP_widget_silverline_tabs extends WP_Widget {

    function WP_widget_silverline_tabs() {
        $widget_ops = array('classname' => 'widget_my_custom_tabs', 'description' => __( "Recent posts with thumbnail, recent comments and tags.") );
        $this->WP_Widget('WP_widget_silverline_tabs', __('SILVERLINE Tabbed Widget'), $widget_ops);
        $this->alt_option_name = 'widget_my_custom_tabs';

        add_action( 'save_post', array(&$this, 'flush_widget_cache') );
        add_action( 'deleted_post', array(&$this, 'flush_widget_cache') );
        add_action( 'switch_theme', array(&$this, 'flush_widget_cache') );
    }

    function widget($args, $instance) {
        $cache = wp_cache_get('widget_silverline_tabs', 'widget');

        if ( !is_array($cache) )
            $cache = array();

        if ( isset($cache[$args['widget_id']]) ) {
            echo $cache[$args['widget_id']];
            return;
        }

        ob_start();
        extract($args);

        $category = apply_filters('category', empty($instance['category']) ? __('0') : $instance['category'], $instance, $this->id_base);
        if ( !$posts = (int) $instance['posts'] )
            $posts = 10;
        else if ( $posts < 1 )
            $posts = 1;
        else if ( $posts > 15 )
            $posts = 15;

		if ( !$comments = (int) $instance['comments'] )
            $comments = 10;
        else if ( $comments < 1 )
            $comments = 1;
        else if ( $$comments > 15 )
            $comments = 15;
            
        

        $r = new WP_Query(array('showposts' => $posts, 'cat' => $category, 'nopaging' => 0, 'post_status' => 'publish', 'ignore_sticky_posts' => true, 'post_type' => array('post', 'custom-post-type')));
        if ($r->have_posts()) :
?>
        <?php echo $before_widget; ?>
        <div class="recent_posts_widget">
     

<style type="text/css">
/* jQuery Fading Tabs: This is all the css that's needed to make it work. The two rules below are generated by the tabs plugin */
.tabs-hide {
display:none; /* hide non-active tabs */
}
.tabs-container {
background:#fff; /* kills fadding in/out IE text bug */ 
}
</style>
        
     



<div id="tabwrap">
  <ul id="tabnav">
    <li class="tabnavlist"><a href="#tab1">Recent Posts</a></li>
    <li class="tabnavlist"><a href="#tab2">Comments</a></li>
    <li class="tabnavlist"><a href="#tab3">Tags</a></li>

  </ul><br/><br/><br/><br/>
  
  
<div style="margin-bottom:-6px;" id="tab1">

        <ul class="widget_ul">
        <?php  while ($r->have_posts()) : $r->the_post(); ?>
        
        <li style="margin-bottom:10px;">
 
     <?php if (has_post_thumbnail()): ?>	
		<?php $image = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), ‘full’ ); ?>		
   			<a class="recent_posts_list" href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', t() ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark"><img class="thumbnail_image" style="margin-right:10px;" align="left" src="<?php bloginfo('template_directory'); ?>/library/js/timthumb.php?src=<?php echo $image[0]; ?>&w=62&h=62&zc=1" />
  		<?php else : ?>
 <a class="recent_posts_list" href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', t() ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark"><img class="thumbnail_image" style="margin-right:10px;" align="left"  src="<?php bloginfo('template_directory'); ?>/library/js/timthumb.php?src=<?php bloginfo('template_directory'); ?>/library/images/no-post-image.png&w=62&h=62&zc=1" />
	<?php endif; ?> 

        <span class="recent_posts_widget_info" href="<?php the_permalink() ?>" title="<?php echo esc_attr(get_the_title() ? get_the_title() : get_the_ID()); ?>"><?php
$tit = the_title('','',FALSE);
echo substr($tit, 0, 45);
if (strlen($tit) > 30) echo "";
?></span></a>
        <span class="recent_posts_widget_date"><p><?php the_time('F j, Y'); ?></p></span>

        </li>
        
        <?php endwhile; ?>
     
       </ul>
       
</div>
  

     <div id="tab2">
<?php
global $wpdb;
$sql = "SELECT DISTINCT ID, post_title, post_password, comment_ID,
comment_post_ID, comment_author, comment_date_gmt, comment_approved,
comment_type,comment_author_url,
SUBSTRING(comment_content,1,30) AS com_excerpt
FROM $wpdb->comments
LEFT OUTER JOIN $wpdb->posts ON ($wpdb->comments.comment_post_ID =
$wpdb->posts.ID)
WHERE comment_approved = '1' AND comment_type = '' AND
post_password = ''
ORDER BY comment_date_gmt DESC
LIMIT $comments";
$comments = $wpdb->get_results($sql);
$output = $pre_HTML;
$output .= "\n<ul>";
foreach ($comments as $comment) {
$output .= "\n<li style=\"height: 26px; border-bottom: 1px dashed #dedede; margin-bottom:8px;\">".strip_tags($comment->comment_author)
.": " . "<a href=\"" . get_permalink($comment->ID) .
"#comment-" . $comment->comment_ID . "\" title=\"on " .
$comment->post_title . "\">" . strip_tags($comment->com_excerpt)
."</a></li>";
}
$output .= "\n</ul>";
$output .= $post_HTML;
echo $output;?>

    </div> 
  

  
    <div style="margin-bottom:-12px;" id="tab3">
		<?php wp_tag_cloud('format=list&smallest=9&largest=9'); ?>
  	</div> 
 
  
  
  
  
		</div>
		</div>
        <?php echo $after_widget; ?>
<?php
        // Reset the global $the_post as this query will have stomped on it
        wp_reset_postdata();

        endif;

        $cache[$args['widget_id']] = ob_get_flush();
        wp_cache_set('widget_silverline_tabs', $cache, 'widget');
    }

    function update( $new_instance, $old_instance ) {
        $instance = $old_instance;
        $instance['posts'] = (int) $new_instance['posts'];
        $instance['comments'] = (int) $new_instance['comments'];
        $instance['category'] = (int) $new_instance['category'];
        $this->flush_widget_cache();

        $alloptions = wp_cache_get( 'alloptions', 'options' );
        if ( isset($alloptions['widget_my_custom_tabs']) )
            delete_option('widget_my_custom_tabs');

        return $instance;
    }

    function flush_widget_cache() {
        wp_cache_delete('widget_silverline_tabs', 'widget');
    }

    function form( $instance ) {
        $category = isset($instance['category']) ? esc_attr($instance['category']) : '';
        if ( !isset($instance['posts']) || !$posts = (int) $instance['posts'] )
            $posts = 6;
        if ( !isset($instance['comments']) || !$comments = (int) $instance['comments'] )
            $comments = 10;
            
         
?>
       
       <p>This widget displays recent posts, recent comments and tags. Do not use this widget twice on a page and do not use in the header or footer widget areas.</p>
       
        <p><label for="<?php echo $this->get_field_id('posts'); ?>"><?php _e('Number of posts to show:'); ?></label>
        <input id="<?php echo $this->get_field_id('posts'); ?>" name="<?php echo $this->get_field_name('posts'); ?>" type="text" value="<?php echo $posts; ?>" size="3" /></p>
        
        <p><label for="<?php echo $this->get_field_id('comments'); ?>"><?php _e('Number of comments to show:'); ?></label>
        <input id="<?php echo $this->get_field_id('comments'); ?>" name="<?php echo $this->get_field_name('comments'); ?>" type="text" value="<?php echo $comments; ?>" size="3" /></p>
     
		<p><label for="<?php echo $this->get_field_id('category'); ?>"><?php _e('Post Category:'); ?></label>  

<?php        
    $id = $this->get_field_id('category');
    $name = $this->get_field_name('category');
    $value = $category;   
    $args = array(
    'show_option_all'   => 'All Categories',
    'orderby'            => 'ID', 
    'order'              => 'ASC',
    'show_count'         => 1,
    'echo'               => 1,
    'selected'           => $value,
    'hierarchical'       => 0, 
    'name'               => $name,
    'id'                 => $id, );
?>
<?php wp_dropdown_categories($args); ?>
</p>
 

<?php
    }
}

register_widget('WP_widget_silverline_tabs');